name: Pull Request Check # 워크플로우 이름

on: # 워크플로우 실행 트리거
  pull_request: # pull_request가 실행 될 때만
    types: [opened, synchronize] # PR 생성되거나 업데이트 될 때

jobs: # 작업정의
  check:
    runs-on: ubuntu-latest # 우분투 환경
    permissions: # 권한 설정
      pull-requests: write # PR 쓰기 권한 설정
    steps: # 작업 단계
      - uses: actions/github-script@v7
        with:
          script: | # script start
            const pull_request = context.payload.pull_request;

            if (pull_request === undefined) {
              console.log("this is not a PR");
              return;
            }

            const body = pull_request.body;

            if (!body) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pull_request.number,
                body: "해당 PR은 가이드라인을 준수하지 않았습니다."
              });
            }
